name: Build and Test Contracts
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
      - name: Install dev dependencies
        run: npm install

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run lint check
        run: npm run lint:check

      - name: Run tests
        run: make test
